### ISSUE TITLE
WFLY8PL-00001: EAR with PicketLink dependencies in submodules fail due to Weld

### ISSUE THREAD

**Issue by arcivanov** [arcivanov/wildfly8-picketlink#1]
The primary set of issues is described here: https://issues.jboss.org/browse/PLINK-666
This is a subset of the problems above:

```
2015-03-10 15:44:31,353 WARN  [org.jboss.as.weld] (default task-1) JBAS016018: Using deployment classloader to load proxy classes for module org.picketlink.core.api:main. Package-private access will not work. To fix this the module should declare dependencies on [org.jboss.weld.core, org.jboss.weld.spi]
2015-03-10 15:44:31,361 ERROR [org.picketlink.http] (default task-1) Exception thrown during processing for path [/test.html]. Sending error with status code [500].: java.lang.IllegalStateException: Could not retrieve fromInstance [@Default Instance<DefaultLoginCredentials>].
  at org.picketlink.http.internal.SecurityFilter.resolveInstance(SecurityFilter.java:564) [picketlink-impl-2.7.0.Final.jar:]
  at org.picketlink.http.internal.SecurityFilter.resolveInstance(SecurityFilter.java:543) [picketlink-impl-2.7.0.Final.jar:]
  at org.picketlink.http.internal.SecurityFilter.getCredentials(SecurityFilter.java:535) [picketlink-impl-2.7.0.Final.jar:]
  at org.picketlink.http.internal.SecurityFilter.createRequestWrapper(SecurityFilter.java:642) [picketlink-impl-2.7.0.Final.jar:]
  at org.picketlink.http.internal.SecurityFilter.doFilter(SecurityFilter.java:162) [picketlink-impl-2.7.0.Final.jar:]
  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_40]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_40]
  at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_40]
Caused by: org.jboss.weld.exceptions.WeldException: WELD-001524: Unable to load proxy class for bean Managed Bean [class org.picketlink.credential.DefaultLoginCredentials] with qualifiers [@Default @Named @Any] with class class org.picketlink.credential.DefaultLoginCredentials using classloader ModuleClassLoader for Module "deployment.scenario4-ear-1.0.0-SNAPSHOT.ear:main" from Service Module Loader
  at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:347) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:298) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:111) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:180) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:170) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ClientProxyProvider.access$100(ClientProxyProvider.java:45) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:56) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.load(ClientProxyProvider.java:52) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
  at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
  at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:74) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:204) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:736) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:762) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.builtin.InstanceImpl.getBeanInstance(InstanceImpl.java:168) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:88) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.picketlink.http.internal.SecurityFilter.resolveInstance(SecurityFilter.java:562) [picketlink-impl-2.7.0.Final.jar:]
  ... 32 more
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/picketlink/idm/credential/Credentials
  at org.jboss.weld.util.bytecode.ClassFileUtils.toClass(ClassFileUtils.java:101) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:463) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:340) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  ... 54 more
Caused by: java.lang.NoClassDefFoundError: org/picketlink/idm/credential/Credentials
  at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.8.0_40]
  at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [rt.jar:1.8.0_40]
  at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) [:1.8.0_40]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_40]
  at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_40]
  at org.jboss.weld.util.bytecode.ClassFileUtils.toClass2(ClassFileUtils.java:108) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  at org.jboss.weld.util.bytecode.ClassFileUtils.toClass(ClassFileUtils.java:97) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
  ... 56 more
Caused by: java.lang.ClassNotFoundException: org.picketlink.idm.credential.Credentials from [Module "deployment.scenario4-ear-1.0.0-SNAPSHOT.ear:main" from Service Module Loader]
  at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.3.Final]
  at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final]
  at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final]
  at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final]
  at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final]
  ... 63 more
```

**Comment by mattalxndr** [comment]
Any progress on this issue? If not, any workaround? We're facing this.

In the ticket, you said "Another gem, which is relatively easy to fix". What is the fix?

**Comment by arcivanov** [comment]
@mattalexx yes. You should get 

http://mvnrepository.com/artifact/biz.ivanov.wildfly/wildfly8-picketlink-module/2.7.0.Final.1

and see https://issues.jboss.org/browse/PLINK-666

Please also see http://ivanov.biz/2015/picketlink-and-ears-on-wildfly/ for in-depth discussion

**Comment by mattalxndr** [comment]
Thanks, that seems to work fine.
